# Generated by Django 4.2.4 on 2023-08-26 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0003_delete_customtoken'),
        ('custom_token', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customtoken',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='custom_token', to='myAdmin.myadmin'),
        ),
    ]
