# Generated by Django 4.2.4 on 2023-08-20 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='students',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
