# Generated by Django 4.2.4 on 2023-08-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professor', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='student.student'),
        ),
        migrations.AddField(
            model_name='professor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='professors_user_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
