# Generated by Django 4.2.4 on 2023-08-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0001_initial'),
        ('professor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='students',
            field=models.ManyToManyField(blank=True, null=True, to='student.student'),
        ),
    ]
