# Generated by Django 4.2.4 on 2023-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professor', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='protests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
