# Generated by Django 4.2.4 on 2023-08-22 09:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('course', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('grade', models.IntegerField()),
                ('courses', models.ManyToManyField(to='course.course')),
                ('professors', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
