# Generated by Django 4.2.4 on 2023-08-28 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='student',
            name='grades',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
