# Generated by Django 4.2.4 on 2023-08-26 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myAdmin', '0002_customtoken'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomToken',
        ),
    ]
